doctor/urls.py
from django.urls import path
from . import views
app_name='doctor'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
] 

home/urls.py
from django.urls import path
from . import views
app_name='home'
urlpatterns = [
    path('', views.home, name='home'),
    path('sing-up/', views.singup, name='singup'),
    path('verify/', views.verify, name='verify'),
    path('lock/', views.lock, name='lock'),
    path('forgot-password/', views.forgotpassword, name='forgotpassword'),
    
] 

mdmadrs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
# from exam import views as auth_view
admin.site.site_header = 'Dashboard'                    # default: "Django Administration"
admin.site.index_title = 'Admin Panel'                 # default: "Site administration"
admin.site.site_title = 'Technologies Admin Panel' # default: "Django site admin"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('doctors/', include('doctor.urls')),
    
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # password reset
    path('reset_password', auth_views.PasswordResetView.as_view(template_name='reset.html'), name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name='sent.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='updatePW.html'), name="password_reset_confirm" ),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="complete.html"), name= "password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns  += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)


doctor/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

patient/models.py
from django.db import models

# Create your models here.

doctor/views.py
from django.shortcuts import render, redirect

# Create your views here.
def dashboard(request):
    context = {

    }
    return render(request, 'doctor/dashboard.html', context)


home/views.py
from django.shortcuts import render, redirect

# Create your views here.
def home(request):
    context = {

    }
    return render(request, 'auth/login.html', context)


def singup(request):
    context = {

    }
    return render(request, 'auth/singup.html', context)

def verify(request):
    context = {

    }
    return render(request, 'auth/verification.html', context)


def lock(request):
    context = {

    }
    return render(request, 'auth/lock.html', context)


def forgotpassword(request):
    context = {

    }
    return render(request, 'auth/forgot_password.html', context)

patient/views.py
from django.shortcuts import render

# Create your views here.

templates/doctor/dashboard.html
{% extends 'doctor/dbase.html' %}
{% load static %}

{% block body %}
<div class="row g-3 justify-content-center">
    <div class="col-md-6 col-xl-4">
      <div class="card card-one">
        <div class="card-body">
          <div class="row">
            <div class="col-7">
              <h3 class="card-value mb-1">4,608</h3>
              <label class="card-title fw-medium text-dark mb-1">Click Through</label>
              <span class="d-block text-muted fs-11 ff-secondary lh-4">No. of clicks to ad that consist of a single impression.</span>
            </div><!-- col -->
            <div class="col-5">
              <div id="apexChart1"></div>
            </div><!-- col -->
          </div><!-- row -->
        </div><!-- card-body -->
      </div><!-- card-one -->
    </div><!-- col -->
    <div class="col-md-6 col-xl-4">
      <div class="card card-one">
        <div class="card-body">
          <div class="row">
            <div class="col-7">
              <h3 class="card-value mb-1">4,868</h3>
              <label class="card-title fw-medium text-dark mb-1">View Through</label>
              <span class="d-block text-muted fs-11 ff-secondary lh-4">Estimated daily unique views per visitor on the ads.</span>
            </div><!-- col -->
            <div class="col-5">
              <div id="apexChart2"></div>
            </div><!-- col -->
          </div><!-- row -->
        </div><!-- card-body -->
      </div><!-- card-one -->
    </div><!-- col -->
    <div class="col-md-6 col-xl-4">
      <div class="card card-one">
        <div class="card-body">
          <div class="row">
            <div class="col-7">
              <h3 class="card-value mb-1">8,785</h3>
              <label class="card-title fw-medium text-dark mb-1">Total Audience</label>
              <span class="d-block text-muted fs-11 ff-secondary lh-4">Estimated total conversions on ads per impressions.</span>
            </div><!-- col -->
            <div class="col-5">
              <div id="apexChart3"></div>
            </div><!-- col -->
          </div><!-- row -->
        </div><!-- card-body -->
      </div><!-- card-one -->
    </div><!-- col -->
    <div class="col-md-7 col-xl-8">
      <div class="card card-one">
        <div class="card-header">
          <h6 class="card-title">Organic Visits &amp; Conversions</h6>
          <nav class="nav nav-icon nav-icon-sm ms-auto">
            <a href="" class="nav-link"><i class="ri-refresh-line"></i></a>
            <a href="" class="nav-link"><i class="ri-more-2-fill"></i></a>
          </nav>
        </div><!-- card-header -->
        <div class="card-body">
          <div id="apexChart4" class="apex-chart-nine"></div>
        </div><!-- card-body -->
      </div><!-- card-one -->
    </div><!-- col -->
        <div class="col-md-5 col-xl-4">
        <div class="card card-one">
            <div class="card-header">
            <h6 class="card-title">Analytics Performance</h6>
            <nav class="nav nav-icon nav-icon-sm ms-auto">
                <a href="" class="nav-link"><i class="ri-refresh-line"></i></a>
                <a href="" class="nav-link"><i class="ri-more-2-fill"></i></a>
            </nav>
            </div><!-- card-header -->
            <div class="card-body p-3">
            <h2 class="performance-value mb-0">9.8 <small class="text-success d-flex align-items-center"><i class="ri-arrow-up-line"></i> 2.8%</small></h2>
            <label class="card-title fs-sm fw-medium">Performance Score</label>
            <div class="progress progress-one ht-8 mt-2 mb-4">
                <div class="progress-bar w-50" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                <div class="progress-bar bg-success w-25" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                <div class="progress-bar bg-orange w-5" role="progressbar" aria-valuenow="5" aria-valuemin="0" aria-valuemax="100"></div>
                <div class="progress-bar bg-pink w-5" role="progressbar" aria-valuenow="5" aria-valuemin="0" aria-valuemax="100"></div>
                <div class="progress-bar bg-info w-10" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
                <div class="progress-bar bg-indigo w-5" role="progressbar" aria-valuenow="5" aria-valuemin="0" aria-valuemax="100"></div>
            </div><!-- progress -->
            <table class="table table-three">
                <tbody>
                <tr>
                    <td><div class="badge-dot bg-primary"></div></td>
                    <td>Excellent</td>
                    <td>3,007</td>
                    <td>50%</td>
                </tr>
                <tr>
                    <td><div class="badge-dot bg-success"></div></td>
                    <td>Very Good</td>
                    <td>1,674</td>
                    <td>25%</td>
                </tr>
                <tr>
                    <td><div class="badge-dot bg-orange"></div></td>
                    <td>Good</td>
                    <td>125</td>
                    <td>6%</td>
                </tr>
                <tr>
                    <td><div class="badge-dot bg-pink"></div></td>
                    <td>Fair</td>
                    <td>98</td>
                    <td>5%</td>
                </tr>
                <tr>
                    <td><div class="badge-dot bg-info"></div></td>
                    <td>Poor</td>
                    <td>512</td>
                    <td>10%</td>
                </tr>
                <tr>
                    <td><div class="badge-dot bg-indigo"></div></td>
                    <td>Very Poor</td>
                    <td>81</td>
                    <td>4%</td>
                </tr>
                </tbody>
            </table>
            </div><!-- card-body -->
        </div><!-- card-one -->
        </div><!-- col -->
</div><!-- row -->

  <div class="card card-one mt-3">
    <div class="card-body p-3">
      <div class="table-responsive">
        <table class="table table-four table-bordered">
          <thead>
            <tr>
              <th>&nbsp;</th>
              <th colspan="3">Acquisition</th>
              <th colspan="3">Behavior</th>
              <th colspan="3">Conversions</th>
            </tr>
            <tr>
              <th>Source</th>
              <th>Users</th>
              <th>New Users</th>
              <th>Sessions</th>
              <th>Bounce Rate</th>
              <th>Pages/Session</th>
              <th>Avg. Session</th>
              <th>Transactions</th>
              <th>Revenue</th>
              <th>Rate</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><a href="">Organic search</a></td>
              <td>350</td>
              <td>22</td>
              <td>5,628</td>
              <td>25.60%</td>
              <td>1.92</td>
              <td>00:01:05</td>
              <td>340,103</td>
              <td>$2.65M</td>
              <td>4.50%</td>
            </tr>
            <tr>
              <td><a href="">Social media</a></td>
              <td>276</td>
              <td>18</td>
              <td>5,100</td>
              <td>23.66%</td>
              <td>1.89</td>
              <td>00:01:03</td>
              <td>321,960</td>
              <td>$2.51M</td>
              <td>4.36%</td>
            </tr>
            <tr>
              <td><a href="">Referral</a></td>
              <td>246</td>
              <td>17</td>
              <td>4,880</td>
              <td>26.22%</td>
              <td>1.78</td>
              <td>00:01:09</td>
              <td>302,767</td>
              <td>$2.1M</td>
              <td>4.34%</td>
            </tr>
            <tr>
              <td><a href="">Email</a></td>
              <td>187</td>
              <td>14</td>
              <td>4,450</td>
              <td>24.97%</td>
              <td>1.35</td>
              <td>00:02:07</td>
              <td>279,300</td>
              <td>$1.86M</td>
              <td>3.99%</td>
            </tr>
            <tr>
              <td><a href="">Other</a></td>
              <td>125</td>
              <td>13</td>
              <td>3,300</td>
              <td>21.67%</td>
              <td>1.14</td>
              <td>00:02:01</td>
              <td>240,200</td>
              <td>$1.51M</td>
              <td>2.84%</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div><!-- card-body -->
  </div><!-- card -->

{% endblock body %}

templates/doctor/dbase.html

<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <!-- Meta -->
    <meta name="description" content="">
    <meta name="author" content="Themepixels">

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">

    <title>MDMA DRS </title>

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="{% static 'lib/remixicon/fonts/remixicon.css' %}">
    <link rel="stylesheet" href="{% static 'lib/jqvmap/jqvmap.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/apexcharts/apexcharts.css' %}">

    <!-- Template CSS -->
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
  </head>
  <body>

    <div class="sidebar">
      <div class="sidebar-header">
        <a href="/" class="sidebar-logo">MDMA Drs</a>
      </div><!-- sidebar-header -->
      <div id="sidebarMenu" class="sidebar-body">
        <div class="nav-group show">
          <a href="#" class="nav-label">Main</a>
          <ul class="nav nav-sidebar">
            
            <li class="nav-item">
              <a href="{% url 'doctor:dashboard' %}" class="nav-link"><i class="ri-pie-chart-2-line"></i> <span>
               Dashboard </span></a>
            </li>
            
          </ul>
        </div><!-- nav-group -->
        <div class="nav-group show">
            <a href="#" class="nav-label">Listings</a>
            <ul class="nav nav-sidebar">
              <li class="nav-item">
                <a href="" class="nav-link "><i class="ri-account-circle-line"></i> <span>Add Listing</span></a>
              </li>
              <li class="nav-item">
                  <a href="" class="nav-link has-sub"><i class="ri-pencil-ruler-2-line"></i> <span>View Listing</span></a>
                  <nav class="nav nav-sub">
                    <a href="#" class="nav-sub-link">Active</a>
                    <a href="#" class="nav-sub-link">Pending</a>
                    <a href="#" class="nav-sub-link">Expried</a>
                  </nav>
                </li>
              <li class="nav-item">
                   <a href="" class="nav-link "><i class="ri-account-circle-line"></i> <span>Coupons</span></a>
              </li>
              <li class="nav-item">
                  <a href="" class="nav-link "><i class="ri-account-circle-line"></i> <span>Reviews</span></a>
             </li>
             
            </ul>
          </div><!-- nav-group -->

        <div class="nav-group show">
          <a href="#" class="nav-label">Applications</a>
          <ul class="nav nav-sidebar">
            <li class="nav-item">
              <a href="#" class="nav-link"><i class="ri-folder-2-line"></i> <span>File Manager</span></a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link"><i class="ri-calendar-line"></i> <span>Calendar</span></a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link"><i class="ri-question-answer-line"></i> <span>Chat</span></a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link"><i class="ri-contacts-book-line"></i> <span>Contacts</span></a>
            </li>
          
            
          </ul>
        </div><!-- nav-group -->
       
        <div class="nav-group show mb-3">
          <a href="#" class="nav-label">Add On</a>
          <ul class="nav nav-sidebar">
            
            <li class="nav-item">
              <a href="" class="nav-link"><i class="ri-suitcase-line"></i> <span>Publish Blog</span></a>
              
            </li>
            
          </ul>
        </div><!-- nav-group -->
      </div><!-- sidebar-body -->
      <div class="sidebar-footer">
        <div class="sidebar-footer-top">
          <div class="sidebar-footer-thumb">
            <img src="{% static 'img/img1.jpg' %}" alt="">
          </div><!-- sidebar-footer-thumb -->
          <div class="sidebar-footer-body">
            <h6><a href="#">Shaira Diaz</a></h6>
            <p>Premium Member</p>
          </div><!-- sidebar-footer-body -->
          <a id="sidebarFooterMenu" href="" class="dropdown-link"><i class="ri-arrow-down-s-line"></i></a>
        </div><!-- sidebar-footer-top -->
        <div class="sidebar-footer-menu">
          <nav class="nav">
            <a href=""><i class="ri-edit-2-line"></i> Edit Profile</a>
            <a href=""><i class="ri-profile-line"></i> View Profile</a>
          </nav>
          <hr>
          <nav class="nav">
            <a href=""><i class="ri-question-line"></i> Help Center</a>
            <a href=""><i class="ri-lock-line"></i> Privacy Settings</a>
            <a href=""><i class="ri-user-settings-line"></i> Account Settings</a>
            <a href=""><i class="ri-logout-box-r-line"></i> Log Out</a>
          </nav>
        </div><!-- sidebar-footer-menu -->
      </div><!-- sidebar-footer -->
    </div><!-- sidebar -->

    <div class="header-main px-3 px-lg-4">
      <a id="menuSidebar" href="#" class="menu-link me-3 me-lg-4"><i class="ri-menu-2-fill"></i></a>

      <div class="form-search me-auto">
        <input type="text" class="form-control" placeholder="Search">
        <i class="ri-search-line"></i>
      </div><!-- form-search -->

   

      <div class="dropdown dropdown-notification ms-3 ms-xl-4">
        <a href="" class="dropdown-link" data-bs-toggle="dropdown" data-bs-auto-close="outside"><small>3</small><i class="ri-notification-3-line"></i></a>
        <div class="dropdown-menu dropdown-menu-end mt-10-f me--10-f">
          <div class="dropdown-menu-header">
            <h6 class="dropdown-menu-title">Notifications</h6>
          </div><!-- dropdown-menu-header -->
          <ul class="list-group">
            <li class="list-group-item">
              <div class="avatar online"><img src="{% static 'img/img10.jpg' %}" alt=""></div>
              <div class="list-group-body">
                <p><strong>Dominador Manuel</strong> and <strong>100 other people</strong> reacted to your comment "Tell your partner that...</p>
                <span>Aug 20 08:55am</span>
              </div><!-- list-group-body -->
            </li>
            <li class="list-group-item">
              <div class="avatar online"><img src="{% static 'img/img11.jpg' %}" alt=""></div>
              <div class="list-group-body">
                <p><strong>Angela Ighot</strong> tagged you and <strong>9 others</strong> in a post.</p>
                <span>Aug 18 10:30am</span>
              </div><!-- list-group-body -->
            </li>
            <li class="list-group-item">
              <div class="avatar"><span class="avatar-initial bg-primary">a</span></div>
              <div class="list-group-body">
                <p>New listings were added that match your search alert <strong>house for rent</strong></p>
                <span>Aug 15 08:10pm</span>
              </div><!-- list-group-body -->
            </li>
            <li class="list-group-item">
              <div class="avatar online"><img src="{% static 'img/img14.jpg' %}" alt=""></div>
              <div class="list-group-body">
                <p>Reminder: <strong>Jerry Cuares</strong> invited you to like <strong>Cuares Surveying Services</strong>. <br><a href="">Accept</a> or <a href="">Decline</a></p>
                <span>Aug 14 11:50pm</span>
              </div><!-- list-group-body -->
            </li>
            
          </ul>
          <div class="dropdown-menu-footer"><a href="">Show all Notifications</a></div>
        </div><!-- dropdown-menu -->
      </div><!-- dropdown -->
      <div class="dropdown dropdown-profile ms-3 ms-xl-4">
          <a href="" class="dropdown-link" data-bs-toggle="dropdown" data-bs-auto-close="outside">
            <div class="avatar online"><img src="{% static 'img/img1.jpg' %}" alt=""></div></a>
          <div class="dropdown-menu dropdown-menu-end mt-10-f">
            <div class="dropdown-menu-body">
              <div class="avatar avatar-xl online mb-3"><img src="{% static 'img/img1.jpg' %}" alt=""></div>
              <h5 class="mb-1 text-dark fw-semibold">Shaira Diaz</h5>
              <p class="fs-sm text-secondary">Premium Member</p>

              <nav class="nav">
                <a href=""><i class="ri-edit-2-line"></i> Edit Profile</a>
                <a href=""><i class="ri-profile-line"></i> View Profile</a>
              </nav>
              <hr>
              <nav class="nav">
                <a href=""><i class="ri-question-line"></i> Help Center</a>
                <a href=""><i class="ri-lock-line"></i> Privacy Settings</a>
                <a href=""><i class="ri-user-settings-line"></i> Account Settings</a>
                <a href=""><i class="ri-logout-box-r-line"></i> Log Out</a>
              </nav>
            </div><!-- dropdown-menu-body -->
          </div><!-- dropdown-menu -->
      </div><!-- dropdown -->
    </div><!-- header-main -->

    <div class="main main-app p-3 p-lg-4">
      <div class="d-flex align-items-center justify-content-between mb-4">
        <div>
          <ol class="breadcrumb fs-sm mb-1">
            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Website Analytics</li>
          </ol>
          <h4 class="main-title mb-0">Welcome to Dashboard</h4>
        </div>
        <nav class="nav nav-icon nav-icon-lg">
          <a href="" class="nav-link" data-bs-toggle="tooltip" title="Share"><i class="ri-share-line"></i></a>
          <a href="" class="nav-link" data-bs-toggle="tooltip" title="Print"><i class="ri-printer-line"></i></a>
          <a href="" class="nav-link" data-bs-toggle="tooltip" title="Report"><i class="ri-bar-chart-2-line"></i></a>
        </nav>
      </div>

      {% block body %}
      
      {% endblock body %}

      <div class="main-footer mt-5">
        <span>&copy; 2023. Dashbyte. All Rights Reserved.</span>
        <span>Created by: <a href="http://themepixels.me" target="_blank">Themepixels</a></span>
      </div><!-- main-footer -->
    </div><!-- main -->


    <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'lib/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'lib/jqvmap/jquery.vmap.min.js' %}"></script>
    <script src="{% static 'lib/jqvmap/maps/jquery.vmap.world.js' %}"></script>
    <script src="{% static 'lib/apexcharts/apexcharts.min.js' %}"></script>

    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/db.data.js' %}"></script>
    <script src="{% static 'js/db.analytics.js' %}"></script>

  </body>
</html>

templates/doctor/temp.html
{% extends 'doctor/dbase.html' %}
{% load static %}

{% block block %}


{% endblock block %}